In [6]:
import numpy as np


In [7]:
ar1=np.array(5)

In [8]:
ar1

array(5)

In [9]:
type(ar1)

numpy.ndarray

In [10]:
ar1=np.array([2,3,4])

In [11]:
ar1

array([2, 3, 4])

In [12]:
ar1=np.array([[2,3,4],[5,6,7]])

In [13]:
ar1

array([[2, 3, 4],
       [5, 6, 7]])

In [14]:
array types:
    
1.zero array
2.ones array
3.empty array
4.array for range

SyntaxError: invalid decimal literal (1512553676.py, line 3)

In [15]:
zero_array=np.zeros([5,6])

In [16]:
zero_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
ar4=np.arange(5)

In [18]:
ar4

array([0, 1, 2, 3, 4])

In [19]:
ar4=np.transpose([[2,3,4],[5,6,7],[8,9,10]])

In [20]:
ar4

array([[ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

In [21]:
a1=np.array([2,2])
a2=np.array([4,4])
a3=np.array([6,6])

In [22]:
a1

array([2, 2])

In [23]:
a2

array([4, 4])

In [24]:
a3

array([6, 6])

In [25]:
concat=np.concatenate((a1,a2))

In [26]:
concat

array([2, 2, 4, 4])

In [27]:
hori=np.hstack((a1,a2))

In [28]:
hori

array([2, 2, 4, 4])

In [30]:
veri=np.hstack((a1,a2))

In [31]:
veri

array([2, 2, 4, 4])